version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: diabetes_db
    environment:
      SA_PASSWORD: "1e2g3e"       
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql
      - ./sql-scripts:/docker-entrypoint-initdb.d

  app:
    build: .
    depends_on:
      - db
    environment:
      
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=diyabet_sistemi;User Id=sa;Password=1e2g3e;"
    ports:
      - "5000:80"
    restart: on-failure

volumes:
  db-data:
